apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
  labels:
    app: deploy-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-app
  template:
    metadata:
      labels:
        app: deploy-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
