apiVersion: v1
kind: Service
metadata:
  name: svc-deploy-app
spec:
  ports:
  - nodePort: 30063
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deploy-app
  type: LoadBalancer
